# Generated by Django 5.0.10 on 2025-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
