# Generated by Django 5.0.14 on 2026-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
