# Generated by Django 5.0.14 on 2026-05-18 15:08

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
        migrations.AddField(
            model_name="post",
            name="cook_time",
            field=models.PositiveIntegerField(
                default=10, help_text="Cooking time in minutes"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="post",
            name="instructions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="prep_time",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Preparation time in minutes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="servings",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of servings the recipe yields"
            ),
            preserve_default=False,
        ),
    ]
