# Generated by Django 6.0.5 on 2026-05-24 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_rename_body_post_description_remove_post_created_at_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Recipe",
        ),
        migrations.RenameIndex(
            model_name="recipe",
            new_name="blog_recipe_publish_8268d9_idx",
            old_name="blog_post_publish_bb7600_idx",
        ),
    ]
